# action.yml
name: 'FontDumpTruck Action Template'
description: 'Template for .Net Framework Action'
author: 'Leland Olney <https://github.com/JohnnyPrimus>'
branding:
  icon: 'book-open'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
