FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2

WORKDIR /app

COPY FontDumpTruck/ .
RUN nuget restore FontDumpTruck.sln
RUN msbuild FontDumpTruck.sln /p:Configuration=Release /p:OutputPath=C:\app\out\

ENTRYPOINT ["C:\\app\\out\\FontDumpTruck.exe"]
